// Dart imports
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// These 'part' files will be generated by build_runner
part 'user_profile.freezed.dart';
part 'user_profile.g.dart';

// Custom converter for handling Firestore Timestamps
class TimestampConverter implements JsonConverter<DateTime, Timestamp> {
  const TimestampConverter();

  @override
  DateTime fromJson(Timestamp timestamp) {
    return timestamp.toDate();
  }

  @override
  Timestamp toJson(DateTime date) => Timestamp.fromDate(date);
}

// Enums can stay as they are
enum AccountCreationStep {
  ACC_STEP_ONBOARDING_PROFILE_CONTACT_INFO,
  ACC_STEP_ONBOARDING_COMPLETE,
}

enum PermissionLevel { PRODUCTION, BETA, DEVELOPER }

@freezed
class UserProfile with _$UserProfile {
  const factory UserProfile({
    @JsonKey(includeToJson: false, includeFromJson: false)
    @Default("")
    String uid,
    @JsonKey(name: 'first_name') required String firstName,
    @JsonKey(name: 'last_name') required String lastName,
    required String email,
    @JsonKey(name: 'email_lowercase') required String emailLowercase,
    @JsonKey(name: 'permission_level')
    @Default(PermissionLevel.PRODUCTION)
    PermissionLevel permissionLevel,
    @JsonKey(name: 'account_creation_time') @Default(0) int accountCreationTime,
    @JsonKey(name: 'date_last_password_change')
    @TimestampConverter()
    required DateTime dateLastPasswordChange,
    @JsonKey(name: 'account_creation_step')
    @Default(AccountCreationStep.ACC_STEP_ONBOARDING_PROFILE_CONTACT_INFO)
    AccountCreationStep accountCreationStep,
  }) = _UserProfile;

  // This factory constructor is used for deserialization
  factory UserProfile.fromJson(Map<String, dynamic> json) =>
      _$UserProfileFromJson(json);

  // Private constructor for adding custom methods/getters
  const UserProfile._();

  // You can keep helper methods like this
  bool get isMissingKeyData =>
      uid.isEmpty || firstName.isEmpty || lastName.isEmpty || email.isEmpty;
  String get wholeName => "$firstName $lastName";
}
